AllCops:
  Exclude:
    - "okuribito_rails.gemspec"
    - "Rakefile"
    - "vendor/**/*"
    - "spec/dummy/**/*"
    - "spec/spec_helper.rb"

Documentation:
  Enabled: false

LineLength:
  Max: 100
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - double_quotes

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - "lib/generators/okuribito_rails/install_generator.rb"

RedundantReturn:
  Exclude:
    - "app/controllers/**/*"

GuardClause:
  MinBodyLength: 4

Style/ActionFilter:
  Exclude:
    - "app/controllers/okuribito_rails/application_controller.rb"
